### ISSUE TITLE
Its called something else now over here: https://www.raspberrypi.org/downloads/raspbian/

### ISSUE THREAD

**Issue by gedw99** [periph/website#11]
Your docs say "Raspbian Stretch lite" over at: https://github.com/periph/website/edit/master/site/content/project/contributing.md
line 58.

But over on the site its called "Raspbian Buster Lite"

**Comment by maruel** [comment]
That's the debian version name. Better to just remove it and name it "Raspbian Lite". Can you send a PR?

**Comment by NeuralSpaz** [comment]
I'm not sure what version of raspbian the RPi gohci nodes are running. https://github.com/periph/gohci They may very well be running stretch. I've not run into any problems related to stretch or buster.

btw, I have some periph stuff running on wheezy and jessie just fine too.

If your looking into setting up a RPi to develop on I would just go with buster.
