### ISSUE TITLE
Driver lifetime management

### ISSUE THREAD

**Issue by different55** [periph/website#18]
The links to "driver lifetime management" on [/project/contributing](https://periph.io/project/contributing) and [/project/goals](https://periph.io/project/goals) are dead ends. It *looks* like it's trying to link to a section on the /project/ index page but flipping through the commit history of that page I can't see that that ever existed.

**Comment by maruel** [comment]
Thanks! I had removed the section in commit cab5e650936a320bb0849b8d21eb05c94b0123b1 but forgot about these links.
